# Prevents duplicate builds from occurring after Travis updates the tag in GitHub
if: tag IS blank

language: java
sudo: false
jdk: openjdk8

jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2"

before_deploy:
  - ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout
  - export project_version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
  - export TRAVIS_TAG=$project_version

before_install:
  - |
    GPG_EXECUTABLE=${GPG_EXECUTABLE:-gpg}
    if [[ -n $GPG_SECRET_KEYS ]]; then
      echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    fi
    if [[ -n $GPG_OWNERTRUST ]]; then
      echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
    fi

install:
  ./mvnw -V dependency:go-offline -B

script: |
  target='verify -Dgpg.skip=true'
  if [[ -n $SONATYPE_PASSWORD ]]; then
    target=deploy
  fi
  ./mvnw -V --settings .maven.xml clean $target -B -U -PbuildKar -Prelease

deploy:
  provider: releases
  api_key:
    secure: IeT3yXlOyQklFs9BjkGkpoGS9g/iPSmKqNc8sNzanTgK4owgUiYHZGmBOUSxsusYo59HidDiEWeNGuNqcZ7Qxzr3LaoZ6BjF8uV9iuoh2HPtLZBQci4vRHu8pC4dmkGC92fbcm8XKMZZmGOuB7X58bO16u2CXLXRw7Ii7km57YqI01nYw7Rasti1DIQcozQ73jB2M9oMUd0CSixIZ5FGe59VLcywdC5kFTMJhUjjbIsuUBl86OXGrP9TupYqF1JuYyqVOU/V4qVnyZrX0Ia071NE1B6R1l+PvjySRgeN7JfOR9GCghRVq+tkwuYlVTCxKGX0IKow2eSPtAGr5+BNxU/xOJiq9HeMC2E2dna0yJ6IlI+pp9nP4Tb74XWx5H4p8Kpg8bGB/61ZZqhZl/OOUUy7qx3uO9KMUdceZy10tUzMl5jcIbs1aVSExmmxQpXHJomvXhkD3Ok6mbKhHU2JJtPo76chLLKxF5axbKYgf29RRy3XfHBCeS9/Mu/Y8SNblbvcOYbmYY7GZER3e5aWB5BFv8DNtrD1w+ZtRCF0PAY3ryxsRNtL9PcDvdL5Eu8/RAC8pYd8HA/adK43jH0XqxMKpn4rqJ3pevy8d6yvPAcT3NZtwQS/nIKDYNpaQ0zdiP2RQNf2JL6hUZuaCuqWi4l4/SLgi4CTEorFJY8Do/s=
  file:
    - target/nexus-repository-puppet-$project_version.jar
    - target/nexus-repository-puppet-$project_version-bundle.kar
  on:
    repo: sonatype-nexus-community/nexus-repository-puppet
    all_branches: true
    condition: $TRAVIS_BRANCH = master
  skip_cleanup: true
  name: $project_version
