#!/bin/bash
#
# Fetch a bunch of Puppet Modules from the Forge for testing

wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-5.1.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-5.0.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.25.1.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.25.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.24.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.23.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.22.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.21.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.20.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.19.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.18.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.17.1.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.17.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.16.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.15.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.14.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.13.1.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.13.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.12.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.11.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.10.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.9.1.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.9.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.8.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.7.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.6.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.5.1.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.5.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.4.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.3.2.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.3.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.2.2.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.2.1.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.2.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.1.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-3.2.2.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-3.2.1.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-3.2.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-3.1.1.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-3.1.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-3.0.1.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-3.0.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-2.6.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-2.5.1.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-2.5.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-2.4.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-2.3.3.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-2.3.2.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-2.3.1.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-2.3.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-2.2.1.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-2.2.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-2.1.3.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-2.0.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-1.1.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-1.0.0.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-0.1.7.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-0.1.6.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-0.1.5.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-0.1.4.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-0.1.3.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-0.1.2.tar.gz
wget https://forge.puppet.com/v3/files/puppetlabs-stdlib-0.1.1.tar.gz